[[constraint]]
	name = "github.com/spf13/viper"
	version = "=1.0.0"

[[constraint]]
	name = "github.com/cosmos/cosmos-sdk"
	version = "=0.22.0"

[[constraint]]
	name = "github.com/stretchr/testify"
	version = "=1.2.1"

[[constraint]]
	name = "github.com/spf13/cobra"
	version = "=0.0.1"

[[override]]
	name = "github.com/golang/protobuf"
	version = "=1.1.0"

[[override]]
	name = "github.com/tendermint/tendermint"
	version = "=0.22.0"

[prune]
	go-tests = true
	unused-packages = true